using System;
using System.Collections.Generic;
using System.Text;

namespace Nglib.VENDORS.OVH.AUTH
{

    /// <summary>
    /// Class representing the result of a previously issued /auth call
    /// </summary>
    public class CredentialResponseModel
    {
        /// <summary>
        /// The URL that the client should visit and enter his credentials
        /// </summary>
        public string validationUrl { get; set; }
        /// <summary>
        /// The consumer key generated by the API. Needed to impersonate the user in subsequent calls
        /// </summary>
        public string consumerKey { get; set; }
    }
}
