//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;
using Nglib.VENDORS.OVH.SHARED;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Threading.Tasks;


// [POST] "/auth/credential"  auth.Credential--accessRules,redirection
//[GET] "/auth/currentCredential"  api.Credential--
//[GET] "/auth/details"  auth.Details--
//[POST] "/auth/logout"  void--
//[GET] "/auth/time"  long--
namespace Nglib.VENDORS.OVH.AUTH {
	
	
	/// <summary>
	/// All states a Credential can be in
	/// </summary>
	public enum AuthCredentialStateEnum {
		
		[EnumMember(Value="expired")]
		Expired,
		
		[EnumMember(Value="pendingValidation")]
		PendingValidation,
		
		[EnumMember(Value="refused")]
		Refused,
		
		[EnumMember(Value="validated")]
		Validated,
	}
	
	/// <summary>
	/// All Authentication methods available
	/// </summary>
	public enum AuthMethodEnum {
		
		[EnumMember(Value="account")]
		Account,
		
		[EnumMember(Value="provider")]
		Provider,
		
		[EnumMember(Value="user")]
		User,
	}
	
	/// <summary>
	/// All HTTP methods available
	/// </summary>
	public enum HttpMethodEnum {
		
		[EnumMember(Value="DELETE")]
		DELETE,
		
		[EnumMember(Value="GET")]
		GET,
		
		[EnumMember(Value="POST")]
		POST,
		
		[EnumMember(Value="PUT")]
		PUT,
	}
	
	/// <summary>
	/// API Credential
	/// </summary>
	public class ApiCredential {
		
		private string[] AllowedIPs_bfield;
		
		private long ApplicationId_bfield;
		
		private System.DateTime Creation_bfield;
		
		private long CredentialId_bfield;
		
		private System.Nullable<System.DateTime> Expiration_bfield;
		
		private System.Nullable<System.DateTime> LastUse_bfield;
		
		private bool OvhSupport_bfield;
		
		private string[] Rules_bfield;
		
		private string Status_bfield;
		
		/// <summary>
		/// If defined, list of ip blocks which are allowed to call API with this credential
		/// {&quot;CanBeNull&quot;:true,&quot;Type&quot;:&quot;ipBlock[]&quot;,&quot;Description&quot;:&quot;If defined, list of ip blocks which are allowed to call API with this credential&quot;,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("allowedIPs")]
		public string[] AllowedIPs {
			get {
				return this.AllowedIPs_bfield;
			}
			set {
				this.AllowedIPs_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;long&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("applicationId")]
		public long ApplicationId {
			get {
				return this.ApplicationId_bfield;
			}
			set {
				this.ApplicationId_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;datetime&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("creation")]
		public System.DateTime Creation {
			get {
				return this.Creation_bfield;
			}
			set {
				this.Creation_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;long&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("credentialId")]
		public long CredentialId {
			get {
				return this.CredentialId_bfield;
			}
			set {
				this.CredentialId_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:true,&quot;Type&quot;:&quot;datetime&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("expiration")]
		public System.Nullable<System.DateTime> Expiration {
			get {
				return this.Expiration_bfield;
			}
			set {
				this.Expiration_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:true,&quot;Type&quot;:&quot;datetime&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("lastUse")]
		public System.Nullable<System.DateTime> LastUse {
			get {
				return this.LastUse_bfield;
			}
			set {
				this.LastUse_bfield = value;
			}
		}
		
		/// <summary>
		/// States whether this credential has been created by yourself or by the OVH support team
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;boolean&quot;,&quot;Description&quot;:&quot;States whether this credential has been created by yourself or by the OVH support team&quot;,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("ovhSupport")]
		public bool OvhSupport {
			get {
				return this.OvhSupport_bfield;
			}
			set {
				this.OvhSupport_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;auth.AccessRule[]&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("rules")]
		public string[] Rules {
			get {
				return this.Rules_bfield;
			}
			set {
				this.Rules_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;auth.CredentialStateEnum&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("status")]
		public string Status {
			get {
				return this.Status_bfield;
			}
			set {
				this.Status_bfield = value;
			}
		}
	}
	
	/// <summary>
	/// Access rule required for the application
	/// </summary>
	public class AuthAccessRule {
		
		private string Method_bfield;
		
		private string Path_bfield;
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;http.MethodEnum&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("method")]
		public string Method {
			get {
				return this.Method_bfield;
			}
			set {
				this.Method_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;string&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("path")]
		public string Path {
			get {
				return this.Path_bfield;
			}
			set {
				this.Path_bfield = value;
			}
		}
	}
	
	/// <summary>
	/// Credential request to get access to the API
	/// </summary>
	public class AuthCredential {
		
		private string ConsumerKey_bfield;
		
		private string State_bfield;
		
		private string ValidationUrl_bfield;
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;string&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("consumerKey")]
		public string ConsumerKey {
			get {
				return this.ConsumerKey_bfield;
			}
			set {
				this.ConsumerKey_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;auth.CredentialStateEnum&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("state")]
		public string State {
			get {
				return this.State_bfield;
			}
			set {
				this.State_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:true,&quot;Type&quot;:&quot;string&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("validationUrl")]
		public string ValidationUrl {
			get {
				return this.ValidationUrl_bfield;
			}
			set {
				this.ValidationUrl_bfield = value;
			}
		}
	}
	
	/// <summary>
	/// Details about the authentication used
	/// </summary>
	public class AuthDetails {
		
		private string Description_bfield;
		
		private string Method_bfield;
		
		private string[] Roles_bfield;
		
		private string User_bfield;
		
		/// <summary>
		/// Description
		/// {&quot;CanBeNull&quot;:true,&quot;Type&quot;:&quot;string&quot;,&quot;Description&quot;:&quot;Description&quot;,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("description")]
		public string Description {
			get {
				return this.Description_bfield;
			}
			set {
				this.Description_bfield = value;
			}
		}
		
		/// <summary>
		/// Authentication method
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;auth.MethodEnum&quot;,&quot;Description&quot;:&quot;Authentication method&quot;,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("method")]
		public string Method {
			get {
				return this.Method_bfield;
			}
			set {
				this.Method_bfield = value;
			}
		}
		
		/// <summary>
		/// Roles
		/// {&quot;CanBeNull&quot;:true,&quot;Type&quot;:&quot;string[]&quot;,&quot;Description&quot;:&quot;Roles&quot;,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("roles")]
		public string[] Roles {
			get {
				return this.Roles_bfield;
			}
			set {
				this.Roles_bfield = value;
			}
		}
		
		/// <summary>
		/// Username
		/// {&quot;CanBeNull&quot;:true,&quot;Type&quot;:&quot;string&quot;,&quot;Description&quot;:&quot;Username&quot;,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("user")]
		public string User {
			get {
				return this.User_bfield;
			}
			set {
				this.User_bfield = value;
			}
		}
	}
}
