//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;
using Nglib.VENDORS.OVH.SHARED;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Threading.Tasks;


// [GET] "/license/cpanel"  string[]--
//[GET] "/license/cpanel/orderableVersions"  license.CpanelOrderConfiguration[]--ip
//[GET] "/license/cpanel/{serviceName}"  license.cpanel.Cpanel--serviceName
//[PUT] "/license/cpanel/{serviceName}"  void--,serviceName
//[GET] "/license/cpanel/{serviceName}/allowedDestinationIp"  ipBlock[]--serviceName
//[GET] "/license/cpanel/{serviceName}/canLicenseBeMovedTo"  license.ChangeIpStatus--destinationIp,serviceName
//[POST] "/license/cpanel/{serviceName}/changeIp"  license.Task--destinationIp,serviceName
//[POST] "/license/cpanel/{serviceName}/confirmTermination"  string--commentary,futureUse,reason,serviceName,token
//[GET] "/license/cpanel/{serviceName}/serviceInfos"  services.Service--serviceName
//[PUT] "/license/cpanel/{serviceName}/serviceInfos"  void--,serviceName
//[GET] "/license/cpanel/{serviceName}/tasks"  long[]--action,serviceName,status
//[GET] "/license/cpanel/{serviceName}/tasks/{taskId}"  license.Task--serviceName,taskId
//[POST] "/license/cpanel/{serviceName}/terminate"  string--serviceName
namespace Nglib.VENDORS.OVH.LICENSECPANEL {
	
	
	/// <summary>
	/// Messages from change IP
	/// </summary>
	public enum LicenseChangeIpMessageEnum {
		
		[EnumMember(Value="OK")]
		OK,
		
		[EnumMember(Value="destinationNotAllowed")]
		DestinationNotAllowed,
		
		[EnumMember(Value="licenseAlreadyExists")]
		LicenseAlreadyExists,
		
		[EnumMember(Value="notAllowedToHandleThis")]
		NotAllowedToHandleThis,
		
		[EnumMember(Value="notSameType")]
		NotSameType,
		
		[EnumMember(Value="sameIp")]
		SameIp,
		
		[EnumMember(Value="versionNotAllowed")]
		VersionNotAllowed,
	}
	
	/// <summary>
	/// All versions available for Cpanel products
	/// </summary>
	public enum LicenseCpanelVersionEnum {
		
		[EnumMember(Value="VERSION_11_FOR_LINUX")]
		VERSION_11_FOR_LINUX,
		
		[EnumMember(Value="VERSION_11_FOR_VIRTUOZZO")]
		VERSION_11_FOR_VIRTUOZZO,
		
		[EnumMember(Value="VERSION_11_FOR_VPS")]
		VERSION_11_FOR_VPS,
		
		[EnumMember(Value="cpanel-license-version-11")]
		Cpanel_license_version_11,
		
		[EnumMember(Value="cpanel-license-version-11-for-virtuozzo")]
		Cpanel_license_version_11_for_virtuozzo,
		
		[EnumMember(Value="cpanel-license-version-11-for-vps")]
		Cpanel_license_version_11_for_vps,
		
		[EnumMember(Value="version-admin-cloud")]
		Version_admin_cloud,
		
		[EnumMember(Value="version-premier-cloud-100")]
		Version_premier_cloud_100,
		
		[EnumMember(Value="version-premier-cloud-1000")]
		Version_premier_cloud_1000,
		
		[EnumMember(Value="version-premier-cloud-10000")]
		Version_premier_cloud_10000,
		
		[EnumMember(Value="version-premier-cloud-1100")]
		Version_premier_cloud_1100,
		
		[EnumMember(Value="version-premier-cloud-1200")]
		Version_premier_cloud_1200,
		
		[EnumMember(Value="version-premier-cloud-1300")]
		Version_premier_cloud_1300,
		
		[EnumMember(Value="version-premier-cloud-1400")]
		Version_premier_cloud_1400,
		
		[EnumMember(Value="version-premier-cloud-1500")]
		Version_premier_cloud_1500,
		
		[EnumMember(Value="version-premier-cloud-1600")]
		Version_premier_cloud_1600,
		
		[EnumMember(Value="version-premier-cloud-1700")]
		Version_premier_cloud_1700,
		
		[EnumMember(Value="version-premier-cloud-1800")]
		Version_premier_cloud_1800,
		
		[EnumMember(Value="version-premier-cloud-1900")]
		Version_premier_cloud_1900,
		
		[EnumMember(Value="version-premier-cloud-200")]
		Version_premier_cloud_200,
		
		[EnumMember(Value="version-premier-cloud-2000")]
		Version_premier_cloud_2000,
		
		[EnumMember(Value="version-premier-cloud-2100")]
		Version_premier_cloud_2100,
		
		[EnumMember(Value="version-premier-cloud-2200")]
		Version_premier_cloud_2200,
		
		[EnumMember(Value="version-premier-cloud-2300")]
		Version_premier_cloud_2300,
		
		[EnumMember(Value="version-premier-cloud-2400")]
		Version_premier_cloud_2400,
		
		[EnumMember(Value="version-premier-cloud-2500")]
		Version_premier_cloud_2500,
		
		[EnumMember(Value="version-premier-cloud-2600")]
		Version_premier_cloud_2600,
		
		[EnumMember(Value="version-premier-cloud-2700")]
		Version_premier_cloud_2700,
		
		[EnumMember(Value="version-premier-cloud-2800")]
		Version_premier_cloud_2800,
		
		[EnumMember(Value="version-premier-cloud-2900")]
		Version_premier_cloud_2900,
		
		[EnumMember(Value="version-premier-cloud-300")]
		Version_premier_cloud_300,
		
		[EnumMember(Value="version-premier-cloud-3000")]
		Version_premier_cloud_3000,
		
		[EnumMember(Value="version-premier-cloud-3100")]
		Version_premier_cloud_3100,
		
		[EnumMember(Value="version-premier-cloud-3200")]
		Version_premier_cloud_3200,
		
		[EnumMember(Value="version-premier-cloud-3300")]
		Version_premier_cloud_3300,
		
		[EnumMember(Value="version-premier-cloud-3400")]
		Version_premier_cloud_3400,
		
		[EnumMember(Value="version-premier-cloud-3500")]
		Version_premier_cloud_3500,
		
		[EnumMember(Value="version-premier-cloud-3600")]
		Version_premier_cloud_3600,
		
		[EnumMember(Value="version-premier-cloud-3700")]
		Version_premier_cloud_3700,
		
		[EnumMember(Value="version-premier-cloud-3800")]
		Version_premier_cloud_3800,
		
		[EnumMember(Value="version-premier-cloud-3900")]
		Version_premier_cloud_3900,
		
		[EnumMember(Value="version-premier-cloud-400")]
		Version_premier_cloud_400,
		
		[EnumMember(Value="version-premier-cloud-4000")]
		Version_premier_cloud_4000,
		
		[EnumMember(Value="version-premier-cloud-4100")]
		Version_premier_cloud_4100,
		
		[EnumMember(Value="version-premier-cloud-4200")]
		Version_premier_cloud_4200,
		
		[EnumMember(Value="version-premier-cloud-4300")]
		Version_premier_cloud_4300,
		
		[EnumMember(Value="version-premier-cloud-4400")]
		Version_premier_cloud_4400,
		
		[EnumMember(Value="version-premier-cloud-4500")]
		Version_premier_cloud_4500,
		
		[EnumMember(Value="version-premier-cloud-4600")]
		Version_premier_cloud_4600,
		
		[EnumMember(Value="version-premier-cloud-4700")]
		Version_premier_cloud_4700,
		
		[EnumMember(Value="version-premier-cloud-4800")]
		Version_premier_cloud_4800,
		
		[EnumMember(Value="version-premier-cloud-4900")]
		Version_premier_cloud_4900,
		
		[EnumMember(Value="version-premier-cloud-500")]
		Version_premier_cloud_500,
		
		[EnumMember(Value="version-premier-cloud-5000")]
		Version_premier_cloud_5000,
		
		[EnumMember(Value="version-premier-cloud-5100")]
		Version_premier_cloud_5100,
		
		[EnumMember(Value="version-premier-cloud-5200")]
		Version_premier_cloud_5200,
		
		[EnumMember(Value="version-premier-cloud-5300")]
		Version_premier_cloud_5300,
		
		[EnumMember(Value="version-premier-cloud-5400")]
		Version_premier_cloud_5400,
		
		[EnumMember(Value="version-premier-cloud-5500")]
		Version_premier_cloud_5500,
		
		[EnumMember(Value="version-premier-cloud-5600")]
		Version_premier_cloud_5600,
		
		[EnumMember(Value="version-premier-cloud-5700")]
		Version_premier_cloud_5700,
		
		[EnumMember(Value="version-premier-cloud-5800")]
		Version_premier_cloud_5800,
		
		[EnumMember(Value="version-premier-cloud-5900")]
		Version_premier_cloud_5900,
		
		[EnumMember(Value="version-premier-cloud-600")]
		Version_premier_cloud_600,
		
		[EnumMember(Value="version-premier-cloud-6000")]
		Version_premier_cloud_6000,
		
		[EnumMember(Value="version-premier-cloud-6100")]
		Version_premier_cloud_6100,
		
		[EnumMember(Value="version-premier-cloud-6200")]
		Version_premier_cloud_6200,
		
		[EnumMember(Value="version-premier-cloud-6300")]
		Version_premier_cloud_6300,
		
		[EnumMember(Value="version-premier-cloud-6400")]
		Version_premier_cloud_6400,
		
		[EnumMember(Value="version-premier-cloud-6500")]
		Version_premier_cloud_6500,
		
		[EnumMember(Value="version-premier-cloud-6600")]
		Version_premier_cloud_6600,
		
		[EnumMember(Value="version-premier-cloud-6700")]
		Version_premier_cloud_6700,
		
		[EnumMember(Value="version-premier-cloud-6800")]
		Version_premier_cloud_6800,
		
		[EnumMember(Value="version-premier-cloud-6900")]
		Version_premier_cloud_6900,
		
		[EnumMember(Value="version-premier-cloud-700")]
		Version_premier_cloud_700,
		
		[EnumMember(Value="version-premier-cloud-7000")]
		Version_premier_cloud_7000,
		
		[EnumMember(Value="version-premier-cloud-7100")]
		Version_premier_cloud_7100,
		
		[EnumMember(Value="version-premier-cloud-7200")]
		Version_premier_cloud_7200,
		
		[EnumMember(Value="version-premier-cloud-7300")]
		Version_premier_cloud_7300,
		
		[EnumMember(Value="version-premier-cloud-7400")]
		Version_premier_cloud_7400,
		
		[EnumMember(Value="version-premier-cloud-7500")]
		Version_premier_cloud_7500,
		
		[EnumMember(Value="version-premier-cloud-7600")]
		Version_premier_cloud_7600,
		
		[EnumMember(Value="version-premier-cloud-7700")]
		Version_premier_cloud_7700,
		
		[EnumMember(Value="version-premier-cloud-7800")]
		Version_premier_cloud_7800,
		
		[EnumMember(Value="version-premier-cloud-7900")]
		Version_premier_cloud_7900,
		
		[EnumMember(Value="version-premier-cloud-800")]
		Version_premier_cloud_800,
		
		[EnumMember(Value="version-premier-cloud-8000")]
		Version_premier_cloud_8000,
		
		[EnumMember(Value="version-premier-cloud-8100")]
		Version_premier_cloud_8100,
		
		[EnumMember(Value="version-premier-cloud-8200")]
		Version_premier_cloud_8200,
		
		[EnumMember(Value="version-premier-cloud-8300")]
		Version_premier_cloud_8300,
		
		[EnumMember(Value="version-premier-cloud-8400")]
		Version_premier_cloud_8400,
		
		[EnumMember(Value="version-premier-cloud-8500")]
		Version_premier_cloud_8500,
		
		[EnumMember(Value="version-premier-cloud-8600")]
		Version_premier_cloud_8600,
		
		[EnumMember(Value="version-premier-cloud-8700")]
		Version_premier_cloud_8700,
		
		[EnumMember(Value="version-premier-cloud-8800")]
		Version_premier_cloud_8800,
		
		[EnumMember(Value="version-premier-cloud-8900")]
		Version_premier_cloud_8900,
		
		[EnumMember(Value="version-premier-cloud-900")]
		Version_premier_cloud_900,
		
		[EnumMember(Value="version-premier-cloud-9000")]
		Version_premier_cloud_9000,
		
		[EnumMember(Value="version-premier-cloud-9100")]
		Version_premier_cloud_9100,
		
		[EnumMember(Value="version-premier-cloud-9200")]
		Version_premier_cloud_9200,
		
		[EnumMember(Value="version-premier-cloud-9300")]
		Version_premier_cloud_9300,
		
		[EnumMember(Value="version-premier-cloud-9400")]
		Version_premier_cloud_9400,
		
		[EnumMember(Value="version-premier-cloud-9500")]
		Version_premier_cloud_9500,
		
		[EnumMember(Value="version-premier-cloud-9600")]
		Version_premier_cloud_9600,
		
		[EnumMember(Value="version-premier-cloud-9700")]
		Version_premier_cloud_9700,
		
		[EnumMember(Value="version-premier-cloud-9800")]
		Version_premier_cloud_9800,
		
		[EnumMember(Value="version-premier-cloud-9900")]
		Version_premier_cloud_9900,
		
		[EnumMember(Value="version-premier-metal-100")]
		Version_premier_metal_100,
		
		[EnumMember(Value="version-premier-metal-1000")]
		Version_premier_metal_1000,
		
		[EnumMember(Value="version-premier-metal-10000")]
		Version_premier_metal_10000,
		
		[EnumMember(Value="version-premier-metal-1100")]
		Version_premier_metal_1100,
		
		[EnumMember(Value="version-premier-metal-1200")]
		Version_premier_metal_1200,
		
		[EnumMember(Value="version-premier-metal-1300")]
		Version_premier_metal_1300,
		
		[EnumMember(Value="version-premier-metal-1400")]
		Version_premier_metal_1400,
		
		[EnumMember(Value="version-premier-metal-1500")]
		Version_premier_metal_1500,
		
		[EnumMember(Value="version-premier-metal-1600")]
		Version_premier_metal_1600,
		
		[EnumMember(Value="version-premier-metal-1700")]
		Version_premier_metal_1700,
		
		[EnumMember(Value="version-premier-metal-1800")]
		Version_premier_metal_1800,
		
		[EnumMember(Value="version-premier-metal-1900")]
		Version_premier_metal_1900,
		
		[EnumMember(Value="version-premier-metal-200")]
		Version_premier_metal_200,
		
		[EnumMember(Value="version-premier-metal-2000")]
		Version_premier_metal_2000,
		
		[EnumMember(Value="version-premier-metal-2100")]
		Version_premier_metal_2100,
		
		[EnumMember(Value="version-premier-metal-2200")]
		Version_premier_metal_2200,
		
		[EnumMember(Value="version-premier-metal-2300")]
		Version_premier_metal_2300,
		
		[EnumMember(Value="version-premier-metal-2400")]
		Version_premier_metal_2400,
		
		[EnumMember(Value="version-premier-metal-2500")]
		Version_premier_metal_2500,
		
		[EnumMember(Value="version-premier-metal-2600")]
		Version_premier_metal_2600,
		
		[EnumMember(Value="version-premier-metal-2700")]
		Version_premier_metal_2700,
		
		[EnumMember(Value="version-premier-metal-2800")]
		Version_premier_metal_2800,
		
		[EnumMember(Value="version-premier-metal-2900")]
		Version_premier_metal_2900,
		
		[EnumMember(Value="version-premier-metal-300")]
		Version_premier_metal_300,
		
		[EnumMember(Value="version-premier-metal-3000")]
		Version_premier_metal_3000,
		
		[EnumMember(Value="version-premier-metal-3100")]
		Version_premier_metal_3100,
		
		[EnumMember(Value="version-premier-metal-3200")]
		Version_premier_metal_3200,
		
		[EnumMember(Value="version-premier-metal-3300")]
		Version_premier_metal_3300,
		
		[EnumMember(Value="version-premier-metal-3400")]
		Version_premier_metal_3400,
		
		[EnumMember(Value="version-premier-metal-3500")]
		Version_premier_metal_3500,
		
		[EnumMember(Value="version-premier-metal-3600")]
		Version_premier_metal_3600,
		
		[EnumMember(Value="version-premier-metal-3700")]
		Version_premier_metal_3700,
		
		[EnumMember(Value="version-premier-metal-3800")]
		Version_premier_metal_3800,
		
		[EnumMember(Value="version-premier-metal-3900")]
		Version_premier_metal_3900,
		
		[EnumMember(Value="version-premier-metal-400")]
		Version_premier_metal_400,
		
		[EnumMember(Value="version-premier-metal-4000")]
		Version_premier_metal_4000,
		
		[EnumMember(Value="version-premier-metal-4100")]
		Version_premier_metal_4100,
		
		[EnumMember(Value="version-premier-metal-4200")]
		Version_premier_metal_4200,
		
		[EnumMember(Value="version-premier-metal-4300")]
		Version_premier_metal_4300,
		
		[EnumMember(Value="version-premier-metal-4400")]
		Version_premier_metal_4400,
		
		[EnumMember(Value="version-premier-metal-4500")]
		Version_premier_metal_4500,
		
		[EnumMember(Value="version-premier-metal-4600")]
		Version_premier_metal_4600,
		
		[EnumMember(Value="version-premier-metal-4700")]
		Version_premier_metal_4700,
		
		[EnumMember(Value="version-premier-metal-4800")]
		Version_premier_metal_4800,
		
		[EnumMember(Value="version-premier-metal-4900")]
		Version_premier_metal_4900,
		
		[EnumMember(Value="version-premier-metal-500")]
		Version_premier_metal_500,
		
		[EnumMember(Value="version-premier-metal-5000")]
		Version_premier_metal_5000,
		
		[EnumMember(Value="version-premier-metal-5100")]
		Version_premier_metal_5100,
		
		[EnumMember(Value="version-premier-metal-5200")]
		Version_premier_metal_5200,
		
		[EnumMember(Value="version-premier-metal-5300")]
		Version_premier_metal_5300,
		
		[EnumMember(Value="version-premier-metal-5400")]
		Version_premier_metal_5400,
		
		[EnumMember(Value="version-premier-metal-5500")]
		Version_premier_metal_5500,
		
		[EnumMember(Value="version-premier-metal-5600")]
		Version_premier_metal_5600,
		
		[EnumMember(Value="version-premier-metal-5700")]
		Version_premier_metal_5700,
		
		[EnumMember(Value="version-premier-metal-5800")]
		Version_premier_metal_5800,
		
		[EnumMember(Value="version-premier-metal-5900")]
		Version_premier_metal_5900,
		
		[EnumMember(Value="version-premier-metal-600")]
		Version_premier_metal_600,
		
		[EnumMember(Value="version-premier-metal-6000")]
		Version_premier_metal_6000,
		
		[EnumMember(Value="version-premier-metal-6100")]
		Version_premier_metal_6100,
		
		[EnumMember(Value="version-premier-metal-6200")]
		Version_premier_metal_6200,
		
		[EnumMember(Value="version-premier-metal-6300")]
		Version_premier_metal_6300,
		
		[EnumMember(Value="version-premier-metal-6400")]
		Version_premier_metal_6400,
		
		[EnumMember(Value="version-premier-metal-6500")]
		Version_premier_metal_6500,
		
		[EnumMember(Value="version-premier-metal-6600")]
		Version_premier_metal_6600,
		
		[EnumMember(Value="version-premier-metal-6700")]
		Version_premier_metal_6700,
		
		[EnumMember(Value="version-premier-metal-6800")]
		Version_premier_metal_6800,
		
		[EnumMember(Value="version-premier-metal-6900")]
		Version_premier_metal_6900,
		
		[EnumMember(Value="version-premier-metal-700")]
		Version_premier_metal_700,
		
		[EnumMember(Value="version-premier-metal-7000")]
		Version_premier_metal_7000,
		
		[EnumMember(Value="version-premier-metal-7100")]
		Version_premier_metal_7100,
		
		[EnumMember(Value="version-premier-metal-7200")]
		Version_premier_metal_7200,
		
		[EnumMember(Value="version-premier-metal-7300")]
		Version_premier_metal_7300,
		
		[EnumMember(Value="version-premier-metal-7400")]
		Version_premier_metal_7400,
		
		[EnumMember(Value="version-premier-metal-7500")]
		Version_premier_metal_7500,
		
		[EnumMember(Value="version-premier-metal-7600")]
		Version_premier_metal_7600,
		
		[EnumMember(Value="version-premier-metal-7700")]
		Version_premier_metal_7700,
		
		[EnumMember(Value="version-premier-metal-7800")]
		Version_premier_metal_7800,
		
		[EnumMember(Value="version-premier-metal-7900")]
		Version_premier_metal_7900,
		
		[EnumMember(Value="version-premier-metal-800")]
		Version_premier_metal_800,
		
		[EnumMember(Value="version-premier-metal-8000")]
		Version_premier_metal_8000,
		
		[EnumMember(Value="version-premier-metal-8100")]
		Version_premier_metal_8100,
		
		[EnumMember(Value="version-premier-metal-8200")]
		Version_premier_metal_8200,
		
		[EnumMember(Value="version-premier-metal-8300")]
		Version_premier_metal_8300,
		
		[EnumMember(Value="version-premier-metal-8400")]
		Version_premier_metal_8400,
		
		[EnumMember(Value="version-premier-metal-8500")]
		Version_premier_metal_8500,
		
		[EnumMember(Value="version-premier-metal-8600")]
		Version_premier_metal_8600,
		
		[EnumMember(Value="version-premier-metal-8700")]
		Version_premier_metal_8700,
		
		[EnumMember(Value="version-premier-metal-8800")]
		Version_premier_metal_8800,
		
		[EnumMember(Value="version-premier-metal-8900")]
		Version_premier_metal_8900,
		
		[EnumMember(Value="version-premier-metal-900")]
		Version_premier_metal_900,
		
		[EnumMember(Value="version-premier-metal-9000")]
		Version_premier_metal_9000,
		
		[EnumMember(Value="version-premier-metal-9100")]
		Version_premier_metal_9100,
		
		[EnumMember(Value="version-premier-metal-9200")]
		Version_premier_metal_9200,
		
		[EnumMember(Value="version-premier-metal-9300")]
		Version_premier_metal_9300,
		
		[EnumMember(Value="version-premier-metal-9400")]
		Version_premier_metal_9400,
		
		[EnumMember(Value="version-premier-metal-9500")]
		Version_premier_metal_9500,
		
		[EnumMember(Value="version-premier-metal-9600")]
		Version_premier_metal_9600,
		
		[EnumMember(Value="version-premier-metal-9700")]
		Version_premier_metal_9700,
		
		[EnumMember(Value="version-premier-metal-9800")]
		Version_premier_metal_9800,
		
		[EnumMember(Value="version-premier-metal-9900")]
		Version_premier_metal_9900,
		
		[EnumMember(Value="version-pro-cloud")]
		Version_pro_cloud,
		
		[EnumMember(Value="version-solo-cloud")]
		Version_solo_cloud,
		
		[EnumMember(Value="version-solo-metal")]
		Version_solo_metal,
	}
	
	/// <summary>
	/// Possible values for license type
	/// </summary>
	public enum LicenseLicenseTypeEnum {
		
		[EnumMember(Value="dedicated")]
		Dedicated,
		
		[EnumMember(Value="dedicatedCloud")]
		DedicatedCloud,
		
		[EnumMember(Value="dedicatedFailover")]
		DedicatedFailover,
		
		[EnumMember(Value="failover")]
		Failover,
		
		[EnumMember(Value="vm")]
		Vm,
		
		[EnumMember(Value="vps")]
		Vps,
		
		[EnumMember(Value="vps_ceph")]
		Vps_ceph,
		
		[EnumMember(Value="vps_classic")]
		Vps_classic,
		
		[EnumMember(Value="vps_cloud")]
		Vps_cloud,
		
		[EnumMember(Value="vps_cloud_2016")]
		Vps_cloud_2016,
		
		[EnumMember(Value="vps_ssd")]
		Vps_ssd,
	}
	
	/// <summary>
	/// All versions available for Cpanel products
	/// </summary>
	public enum LicenseOrderableCpanelVersionEnum {
		
		[EnumMember(Value="VERSION_11_FOR_LINUX")]
		VERSION_11_FOR_LINUX,
		
		[EnumMember(Value="VERSION_11_FOR_VIRTUOZZO")]
		VERSION_11_FOR_VIRTUOZZO,
		
		[EnumMember(Value="VERSION_11_FOR_VPS")]
		VERSION_11_FOR_VPS,
		
		[EnumMember(Value="cpanel-license-premier-cloud-1000-accounts")]
		Cpanel_license_premier_cloud_1000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-10000-accounts")]
		Cpanel_license_premier_cloud_10000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-1100-accounts")]
		Cpanel_license_premier_cloud_1100_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-1200-accounts")]
		Cpanel_license_premier_cloud_1200_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-1300-accounts")]
		Cpanel_license_premier_cloud_1300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-1400-accounts")]
		Cpanel_license_premier_cloud_1400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-1500-accounts")]
		Cpanel_license_premier_cloud_1500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-1600-accounts")]
		Cpanel_license_premier_cloud_1600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-1700-accounts")]
		Cpanel_license_premier_cloud_1700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-1800-accounts")]
		Cpanel_license_premier_cloud_1800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-1900-accounts")]
		Cpanel_license_premier_cloud_1900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-2000-accounts")]
		Cpanel_license_premier_cloud_2000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-2100-accounts")]
		Cpanel_license_premier_cloud_2100_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-2200-accounts")]
		Cpanel_license_premier_cloud_2200_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-2300-accounts")]
		Cpanel_license_premier_cloud_2300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-2400-accounts")]
		Cpanel_license_premier_cloud_2400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-2500-accounts")]
		Cpanel_license_premier_cloud_2500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-2600-accounts")]
		Cpanel_license_premier_cloud_2600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-2700-accounts")]
		Cpanel_license_premier_cloud_2700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-2800-accounts")]
		Cpanel_license_premier_cloud_2800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-2900-accounts")]
		Cpanel_license_premier_cloud_2900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-300-accounts")]
		Cpanel_license_premier_cloud_300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-3000-accounts")]
		Cpanel_license_premier_cloud_3000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-3100-accounts")]
		Cpanel_license_premier_cloud_3100_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-3200-accounts")]
		Cpanel_license_premier_cloud_3200_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-3300-accounts")]
		Cpanel_license_premier_cloud_3300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-3400-accounts")]
		Cpanel_license_premier_cloud_3400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-3500-accounts")]
		Cpanel_license_premier_cloud_3500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-3600-accounts")]
		Cpanel_license_premier_cloud_3600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-3700-accounts")]
		Cpanel_license_premier_cloud_3700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-3800-accounts")]
		Cpanel_license_premier_cloud_3800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-3900-accounts")]
		Cpanel_license_premier_cloud_3900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-400-accounts")]
		Cpanel_license_premier_cloud_400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-4000-accounts")]
		Cpanel_license_premier_cloud_4000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-4100-accounts")]
		Cpanel_license_premier_cloud_4100_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-4200-accounts")]
		Cpanel_license_premier_cloud_4200_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-4300-accounts")]
		Cpanel_license_premier_cloud_4300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-4400-accounts")]
		Cpanel_license_premier_cloud_4400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-4500-accounts")]
		Cpanel_license_premier_cloud_4500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-4600-accounts")]
		Cpanel_license_premier_cloud_4600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-4700-accounts")]
		Cpanel_license_premier_cloud_4700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-4800-accounts")]
		Cpanel_license_premier_cloud_4800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-4900-accounts")]
		Cpanel_license_premier_cloud_4900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-500-accounts")]
		Cpanel_license_premier_cloud_500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-5000-accounts")]
		Cpanel_license_premier_cloud_5000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-5100-accounts")]
		Cpanel_license_premier_cloud_5100_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-5200-accounts")]
		Cpanel_license_premier_cloud_5200_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-5300-accounts")]
		Cpanel_license_premier_cloud_5300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-5400-accounts")]
		Cpanel_license_premier_cloud_5400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-5500-accounts")]
		Cpanel_license_premier_cloud_5500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-5600-accounts")]
		Cpanel_license_premier_cloud_5600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-5700-accounts")]
		Cpanel_license_premier_cloud_5700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-5800-accounts")]
		Cpanel_license_premier_cloud_5800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-5900-accounts")]
		Cpanel_license_premier_cloud_5900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-600-accounts")]
		Cpanel_license_premier_cloud_600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-6000-accounts")]
		Cpanel_license_premier_cloud_6000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-6100-accounts")]
		Cpanel_license_premier_cloud_6100_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-6200-accounts")]
		Cpanel_license_premier_cloud_6200_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-6300-accounts")]
		Cpanel_license_premier_cloud_6300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-6400-accounts")]
		Cpanel_license_premier_cloud_6400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-6500-accounts")]
		Cpanel_license_premier_cloud_6500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-6600-accounts")]
		Cpanel_license_premier_cloud_6600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-6700-accounts")]
		Cpanel_license_premier_cloud_6700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-6800-accounts")]
		Cpanel_license_premier_cloud_6800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-6900-accounts")]
		Cpanel_license_premier_cloud_6900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-700-accounts")]
		Cpanel_license_premier_cloud_700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-7000-accounts")]
		Cpanel_license_premier_cloud_7000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-7100-accounts")]
		Cpanel_license_premier_cloud_7100_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-7200-accounts")]
		Cpanel_license_premier_cloud_7200_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-7300-accounts")]
		Cpanel_license_premier_cloud_7300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-7400-accounts")]
		Cpanel_license_premier_cloud_7400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-7500-accounts")]
		Cpanel_license_premier_cloud_7500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-7600-accounts")]
		Cpanel_license_premier_cloud_7600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-7700-accounts")]
		Cpanel_license_premier_cloud_7700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-7800-accounts")]
		Cpanel_license_premier_cloud_7800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-7900-accounts")]
		Cpanel_license_premier_cloud_7900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-800-accounts")]
		Cpanel_license_premier_cloud_800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-8000-accounts")]
		Cpanel_license_premier_cloud_8000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-8100-accounts")]
		Cpanel_license_premier_cloud_8100_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-8200-accounts")]
		Cpanel_license_premier_cloud_8200_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-8300-accounts")]
		Cpanel_license_premier_cloud_8300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-8400-accounts")]
		Cpanel_license_premier_cloud_8400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-8500-accounts")]
		Cpanel_license_premier_cloud_8500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-8600-accounts")]
		Cpanel_license_premier_cloud_8600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-8700-accounts")]
		Cpanel_license_premier_cloud_8700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-8800-accounts")]
		Cpanel_license_premier_cloud_8800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-8900-accounts")]
		Cpanel_license_premier_cloud_8900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-900-accounts")]
		Cpanel_license_premier_cloud_900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-9000-accounts")]
		Cpanel_license_premier_cloud_9000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-9100-accounts")]
		Cpanel_license_premier_cloud_9100_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-9200-accounts")]
		Cpanel_license_premier_cloud_9200_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-9300-accounts")]
		Cpanel_license_premier_cloud_9300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-9400-accounts")]
		Cpanel_license_premier_cloud_9400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-9500-accounts")]
		Cpanel_license_premier_cloud_9500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-9600-accounts")]
		Cpanel_license_premier_cloud_9600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-9700-accounts")]
		Cpanel_license_premier_cloud_9700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-9800-accounts")]
		Cpanel_license_premier_cloud_9800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-cloud-9900-accounts")]
		Cpanel_license_premier_cloud_9900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-1000-accounts")]
		Cpanel_license_premier_metal_1000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-10000-accounts")]
		Cpanel_license_premier_metal_10000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-1100-accounts")]
		Cpanel_license_premier_metal_1100_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-1200-accounts")]
		Cpanel_license_premier_metal_1200_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-1300-accounts")]
		Cpanel_license_premier_metal_1300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-1400-accounts")]
		Cpanel_license_premier_metal_1400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-1500-accounts")]
		Cpanel_license_premier_metal_1500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-1600-accounts")]
		Cpanel_license_premier_metal_1600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-1700-accounts")]
		Cpanel_license_premier_metal_1700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-1800-accounts")]
		Cpanel_license_premier_metal_1800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-1900-accounts")]
		Cpanel_license_premier_metal_1900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-2000-accounts")]
		Cpanel_license_premier_metal_2000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-2100-accounts")]
		Cpanel_license_premier_metal_2100_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-2200-accounts")]
		Cpanel_license_premier_metal_2200_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-2300-accounts")]
		Cpanel_license_premier_metal_2300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-2400-accounts")]
		Cpanel_license_premier_metal_2400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-2500-accounts")]
		Cpanel_license_premier_metal_2500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-2600-accounts")]
		Cpanel_license_premier_metal_2600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-2700-accounts")]
		Cpanel_license_premier_metal_2700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-2800-accounts")]
		Cpanel_license_premier_metal_2800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-2900-accounts")]
		Cpanel_license_premier_metal_2900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-300-accounts")]
		Cpanel_license_premier_metal_300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-3000-accounts")]
		Cpanel_license_premier_metal_3000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-3100-accounts")]
		Cpanel_license_premier_metal_3100_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-3200-accounts")]
		Cpanel_license_premier_metal_3200_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-3300-accounts")]
		Cpanel_license_premier_metal_3300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-3400-accounts")]
		Cpanel_license_premier_metal_3400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-3500-accounts")]
		Cpanel_license_premier_metal_3500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-3600-accounts")]
		Cpanel_license_premier_metal_3600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-3700-accounts")]
		Cpanel_license_premier_metal_3700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-3800-accounts")]
		Cpanel_license_premier_metal_3800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-3900-accounts")]
		Cpanel_license_premier_metal_3900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-400-accounts")]
		Cpanel_license_premier_metal_400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-4000-accounts")]
		Cpanel_license_premier_metal_4000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-4100-accounts")]
		Cpanel_license_premier_metal_4100_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-4200-accounts")]
		Cpanel_license_premier_metal_4200_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-4300-accounts")]
		Cpanel_license_premier_metal_4300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-4400-accounts")]
		Cpanel_license_premier_metal_4400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-4500-accounts")]
		Cpanel_license_premier_metal_4500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-4600-accounts")]
		Cpanel_license_premier_metal_4600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-4700-accounts")]
		Cpanel_license_premier_metal_4700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-4800-accounts")]
		Cpanel_license_premier_metal_4800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-4900-accounts")]
		Cpanel_license_premier_metal_4900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-500-accounts")]
		Cpanel_license_premier_metal_500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-5000-accounts")]
		Cpanel_license_premier_metal_5000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-5100-accounts")]
		Cpanel_license_premier_metal_5100_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-5200-accounts")]
		Cpanel_license_premier_metal_5200_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-5300-accounts")]
		Cpanel_license_premier_metal_5300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-5400-accounts")]
		Cpanel_license_premier_metal_5400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-5500-accounts")]
		Cpanel_license_premier_metal_5500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-5600-accounts")]
		Cpanel_license_premier_metal_5600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-5700-accounts")]
		Cpanel_license_premier_metal_5700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-5800-accounts")]
		Cpanel_license_premier_metal_5800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-5900-accounts")]
		Cpanel_license_premier_metal_5900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-600-accounts")]
		Cpanel_license_premier_metal_600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-6000-accounts")]
		Cpanel_license_premier_metal_6000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-6100-accounts")]
		Cpanel_license_premier_metal_6100_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-6200-accounts")]
		Cpanel_license_premier_metal_6200_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-6300-accounts")]
		Cpanel_license_premier_metal_6300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-6400-accounts")]
		Cpanel_license_premier_metal_6400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-6500-accounts")]
		Cpanel_license_premier_metal_6500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-6600-accounts")]
		Cpanel_license_premier_metal_6600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-6700-accounts")]
		Cpanel_license_premier_metal_6700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-6800-accounts")]
		Cpanel_license_premier_metal_6800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-6900-accounts")]
		Cpanel_license_premier_metal_6900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-700-accounts")]
		Cpanel_license_premier_metal_700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-7000-accounts")]
		Cpanel_license_premier_metal_7000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-7100-accounts")]
		Cpanel_license_premier_metal_7100_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-7200-accounts")]
		Cpanel_license_premier_metal_7200_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-7300-accounts")]
		Cpanel_license_premier_metal_7300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-7400-accounts")]
		Cpanel_license_premier_metal_7400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-7500-accounts")]
		Cpanel_license_premier_metal_7500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-7600-accounts")]
		Cpanel_license_premier_metal_7600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-7700-accounts")]
		Cpanel_license_premier_metal_7700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-7800-accounts")]
		Cpanel_license_premier_metal_7800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-7900-accounts")]
		Cpanel_license_premier_metal_7900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-800-accounts")]
		Cpanel_license_premier_metal_800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-8000-accounts")]
		Cpanel_license_premier_metal_8000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-8100-accounts")]
		Cpanel_license_premier_metal_8100_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-8200-accounts")]
		Cpanel_license_premier_metal_8200_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-8300-accounts")]
		Cpanel_license_premier_metal_8300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-8400-accounts")]
		Cpanel_license_premier_metal_8400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-8500-accounts")]
		Cpanel_license_premier_metal_8500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-8600-accounts")]
		Cpanel_license_premier_metal_8600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-8700-accounts")]
		Cpanel_license_premier_metal_8700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-8800-accounts")]
		Cpanel_license_premier_metal_8800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-8900-accounts")]
		Cpanel_license_premier_metal_8900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-900-accounts")]
		Cpanel_license_premier_metal_900_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-9000-accounts")]
		Cpanel_license_premier_metal_9000_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-9100-accounts")]
		Cpanel_license_premier_metal_9100_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-9200-accounts")]
		Cpanel_license_premier_metal_9200_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-9300-accounts")]
		Cpanel_license_premier_metal_9300_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-9400-accounts")]
		Cpanel_license_premier_metal_9400_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-9500-accounts")]
		Cpanel_license_premier_metal_9500_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-9600-accounts")]
		Cpanel_license_premier_metal_9600_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-9700-accounts")]
		Cpanel_license_premier_metal_9700_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-9800-accounts")]
		Cpanel_license_premier_metal_9800_accounts,
		
		[EnumMember(Value="cpanel-license-premier-metal-9900-accounts")]
		Cpanel_license_premier_metal_9900_accounts,
		
		[EnumMember(Value="cpanel-license-version-11")]
		Cpanel_license_version_11,
		
		[EnumMember(Value="cpanel-license-version-11-for-virtuozzo")]
		Cpanel_license_version_11_for_virtuozzo,
		
		[EnumMember(Value="cpanel-license-version-11-for-vps")]
		Cpanel_license_version_11_for_vps,
		
		[EnumMember(Value="version-admin-cloud")]
		Version_admin_cloud,
		
		[EnumMember(Value="version-premier-cloud-100")]
		Version_premier_cloud_100,
		
		[EnumMember(Value="version-premier-cloud-1000")]
		Version_premier_cloud_1000,
		
		[EnumMember(Value="version-premier-cloud-10000")]
		Version_premier_cloud_10000,
		
		[EnumMember(Value="version-premier-cloud-1100")]
		Version_premier_cloud_1100,
		
		[EnumMember(Value="version-premier-cloud-1200")]
		Version_premier_cloud_1200,
		
		[EnumMember(Value="version-premier-cloud-1300")]
		Version_premier_cloud_1300,
		
		[EnumMember(Value="version-premier-cloud-1400")]
		Version_premier_cloud_1400,
		
		[EnumMember(Value="version-premier-cloud-1500")]
		Version_premier_cloud_1500,
		
		[EnumMember(Value="version-premier-cloud-1600")]
		Version_premier_cloud_1600,
		
		[EnumMember(Value="version-premier-cloud-1700")]
		Version_premier_cloud_1700,
		
		[EnumMember(Value="version-premier-cloud-1800")]
		Version_premier_cloud_1800,
		
		[EnumMember(Value="version-premier-cloud-1900")]
		Version_premier_cloud_1900,
		
		[EnumMember(Value="version-premier-cloud-200")]
		Version_premier_cloud_200,
		
		[EnumMember(Value="version-premier-cloud-2000")]
		Version_premier_cloud_2000,
		
		[EnumMember(Value="version-premier-cloud-2100")]
		Version_premier_cloud_2100,
		
		[EnumMember(Value="version-premier-cloud-2200")]
		Version_premier_cloud_2200,
		
		[EnumMember(Value="version-premier-cloud-2300")]
		Version_premier_cloud_2300,
		
		[EnumMember(Value="version-premier-cloud-2400")]
		Version_premier_cloud_2400,
		
		[EnumMember(Value="version-premier-cloud-2500")]
		Version_premier_cloud_2500,
		
		[EnumMember(Value="version-premier-cloud-2600")]
		Version_premier_cloud_2600,
		
		[EnumMember(Value="version-premier-cloud-2700")]
		Version_premier_cloud_2700,
		
		[EnumMember(Value="version-premier-cloud-2800")]
		Version_premier_cloud_2800,
		
		[EnumMember(Value="version-premier-cloud-2900")]
		Version_premier_cloud_2900,
		
		[EnumMember(Value="version-premier-cloud-300")]
		Version_premier_cloud_300,
		
		[EnumMember(Value="version-premier-cloud-3000")]
		Version_premier_cloud_3000,
		
		[EnumMember(Value="version-premier-cloud-3100")]
		Version_premier_cloud_3100,
		
		[EnumMember(Value="version-premier-cloud-3200")]
		Version_premier_cloud_3200,
		
		[EnumMember(Value="version-premier-cloud-3300")]
		Version_premier_cloud_3300,
		
		[EnumMember(Value="version-premier-cloud-3400")]
		Version_premier_cloud_3400,
		
		[EnumMember(Value="version-premier-cloud-3500")]
		Version_premier_cloud_3500,
		
		[EnumMember(Value="version-premier-cloud-3600")]
		Version_premier_cloud_3600,
		
		[EnumMember(Value="version-premier-cloud-3700")]
		Version_premier_cloud_3700,
		
		[EnumMember(Value="version-premier-cloud-3800")]
		Version_premier_cloud_3800,
		
		[EnumMember(Value="version-premier-cloud-3900")]
		Version_premier_cloud_3900,
		
		[EnumMember(Value="version-premier-cloud-400")]
		Version_premier_cloud_400,
		
		[EnumMember(Value="version-premier-cloud-4000")]
		Version_premier_cloud_4000,
		
		[EnumMember(Value="version-premier-cloud-4100")]
		Version_premier_cloud_4100,
		
		[EnumMember(Value="version-premier-cloud-4200")]
		Version_premier_cloud_4200,
		
		[EnumMember(Value="version-premier-cloud-4300")]
		Version_premier_cloud_4300,
		
		[EnumMember(Value="version-premier-cloud-4400")]
		Version_premier_cloud_4400,
		
		[EnumMember(Value="version-premier-cloud-4500")]
		Version_premier_cloud_4500,
		
		[EnumMember(Value="version-premier-cloud-4600")]
		Version_premier_cloud_4600,
		
		[EnumMember(Value="version-premier-cloud-4700")]
		Version_premier_cloud_4700,
		
		[EnumMember(Value="version-premier-cloud-4800")]
		Version_premier_cloud_4800,
		
		[EnumMember(Value="version-premier-cloud-4900")]
		Version_premier_cloud_4900,
		
		[EnumMember(Value="version-premier-cloud-500")]
		Version_premier_cloud_500,
		
		[EnumMember(Value="version-premier-cloud-5000")]
		Version_premier_cloud_5000,
		
		[EnumMember(Value="version-premier-cloud-5100")]
		Version_premier_cloud_5100,
		
		[EnumMember(Value="version-premier-cloud-5200")]
		Version_premier_cloud_5200,
		
		[EnumMember(Value="version-premier-cloud-5300")]
		Version_premier_cloud_5300,
		
		[EnumMember(Value="version-premier-cloud-5400")]
		Version_premier_cloud_5400,
		
		[EnumMember(Value="version-premier-cloud-5500")]
		Version_premier_cloud_5500,
		
		[EnumMember(Value="version-premier-cloud-5600")]
		Version_premier_cloud_5600,
		
		[EnumMember(Value="version-premier-cloud-5700")]
		Version_premier_cloud_5700,
		
		[EnumMember(Value="version-premier-cloud-5800")]
		Version_premier_cloud_5800,
		
		[EnumMember(Value="version-premier-cloud-5900")]
		Version_premier_cloud_5900,
		
		[EnumMember(Value="version-premier-cloud-600")]
		Version_premier_cloud_600,
		
		[EnumMember(Value="version-premier-cloud-6000")]
		Version_premier_cloud_6000,
		
		[EnumMember(Value="version-premier-cloud-6100")]
		Version_premier_cloud_6100,
		
		[EnumMember(Value="version-premier-cloud-6200")]
		Version_premier_cloud_6200,
		
		[EnumMember(Value="version-premier-cloud-6300")]
		Version_premier_cloud_6300,
		
		[EnumMember(Value="version-premier-cloud-6400")]
		Version_premier_cloud_6400,
		
		[EnumMember(Value="version-premier-cloud-6500")]
		Version_premier_cloud_6500,
		
		[EnumMember(Value="version-premier-cloud-6600")]
		Version_premier_cloud_6600,
		
		[EnumMember(Value="version-premier-cloud-6700")]
		Version_premier_cloud_6700,
		
		[EnumMember(Value="version-premier-cloud-6800")]
		Version_premier_cloud_6800,
		
		[EnumMember(Value="version-premier-cloud-6900")]
		Version_premier_cloud_6900,
		
		[EnumMember(Value="version-premier-cloud-700")]
		Version_premier_cloud_700,
		
		[EnumMember(Value="version-premier-cloud-7000")]
		Version_premier_cloud_7000,
		
		[EnumMember(Value="version-premier-cloud-7100")]
		Version_premier_cloud_7100,
		
		[EnumMember(Value="version-premier-cloud-7200")]
		Version_premier_cloud_7200,
		
		[EnumMember(Value="version-premier-cloud-7300")]
		Version_premier_cloud_7300,
		
		[EnumMember(Value="version-premier-cloud-7400")]
		Version_premier_cloud_7400,
		
		[EnumMember(Value="version-premier-cloud-7500")]
		Version_premier_cloud_7500,
		
		[EnumMember(Value="version-premier-cloud-7600")]
		Version_premier_cloud_7600,
		
		[EnumMember(Value="version-premier-cloud-7700")]
		Version_premier_cloud_7700,
		
		[EnumMember(Value="version-premier-cloud-7800")]
		Version_premier_cloud_7800,
		
		[EnumMember(Value="version-premier-cloud-7900")]
		Version_premier_cloud_7900,
		
		[EnumMember(Value="version-premier-cloud-800")]
		Version_premier_cloud_800,
		
		[EnumMember(Value="version-premier-cloud-8000")]
		Version_premier_cloud_8000,
		
		[EnumMember(Value="version-premier-cloud-8100")]
		Version_premier_cloud_8100,
		
		[EnumMember(Value="version-premier-cloud-8200")]
		Version_premier_cloud_8200,
		
		[EnumMember(Value="version-premier-cloud-8300")]
		Version_premier_cloud_8300,
		
		[EnumMember(Value="version-premier-cloud-8400")]
		Version_premier_cloud_8400,
		
		[EnumMember(Value="version-premier-cloud-8500")]
		Version_premier_cloud_8500,
		
		[EnumMember(Value="version-premier-cloud-8600")]
		Version_premier_cloud_8600,
		
		[EnumMember(Value="version-premier-cloud-8700")]
		Version_premier_cloud_8700,
		
		[EnumMember(Value="version-premier-cloud-8800")]
		Version_premier_cloud_8800,
		
		[EnumMember(Value="version-premier-cloud-8900")]
		Version_premier_cloud_8900,
		
		[EnumMember(Value="version-premier-cloud-900")]
		Version_premier_cloud_900,
		
		[EnumMember(Value="version-premier-cloud-9000")]
		Version_premier_cloud_9000,
		
		[EnumMember(Value="version-premier-cloud-9100")]
		Version_premier_cloud_9100,
		
		[EnumMember(Value="version-premier-cloud-9200")]
		Version_premier_cloud_9200,
		
		[EnumMember(Value="version-premier-cloud-9300")]
		Version_premier_cloud_9300,
		
		[EnumMember(Value="version-premier-cloud-9400")]
		Version_premier_cloud_9400,
		
		[EnumMember(Value="version-premier-cloud-9500")]
		Version_premier_cloud_9500,
		
		[EnumMember(Value="version-premier-cloud-9600")]
		Version_premier_cloud_9600,
		
		[EnumMember(Value="version-premier-cloud-9700")]
		Version_premier_cloud_9700,
		
		[EnumMember(Value="version-premier-cloud-9800")]
		Version_premier_cloud_9800,
		
		[EnumMember(Value="version-premier-cloud-9900")]
		Version_premier_cloud_9900,
		
		[EnumMember(Value="version-premier-metal-1000")]
		Version_premier_metal_1000,
		
		[EnumMember(Value="version-premier-metal-10000")]
		Version_premier_metal_10000,
		
		[EnumMember(Value="version-premier-metal-1100")]
		Version_premier_metal_1100,
		
		[EnumMember(Value="version-premier-metal-1200")]
		Version_premier_metal_1200,
		
		[EnumMember(Value="version-premier-metal-1300")]
		Version_premier_metal_1300,
		
		[EnumMember(Value="version-premier-metal-1400")]
		Version_premier_metal_1400,
		
		[EnumMember(Value="version-premier-metal-1500")]
		Version_premier_metal_1500,
		
		[EnumMember(Value="version-premier-metal-1600")]
		Version_premier_metal_1600,
		
		[EnumMember(Value="version-premier-metal-1700")]
		Version_premier_metal_1700,
		
		[EnumMember(Value="version-premier-metal-1800")]
		Version_premier_metal_1800,
		
		[EnumMember(Value="version-premier-metal-1900")]
		Version_premier_metal_1900,
		
		[EnumMember(Value="version-premier-metal-2000")]
		Version_premier_metal_2000,
		
		[EnumMember(Value="version-premier-metal-2100")]
		Version_premier_metal_2100,
		
		[EnumMember(Value="version-premier-metal-2200")]
		Version_premier_metal_2200,
		
		[EnumMember(Value="version-premier-metal-2300")]
		Version_premier_metal_2300,
		
		[EnumMember(Value="version-premier-metal-2400")]
		Version_premier_metal_2400,
		
		[EnumMember(Value="version-premier-metal-2500")]
		Version_premier_metal_2500,
		
		[EnumMember(Value="version-premier-metal-2600")]
		Version_premier_metal_2600,
		
		[EnumMember(Value="version-premier-metal-2700")]
		Version_premier_metal_2700,
		
		[EnumMember(Value="version-premier-metal-2800")]
		Version_premier_metal_2800,
		
		[EnumMember(Value="version-premier-metal-2900")]
		Version_premier_metal_2900,
		
		[EnumMember(Value="version-premier-metal-300")]
		Version_premier_metal_300,
		
		[EnumMember(Value="version-premier-metal-3000")]
		Version_premier_metal_3000,
		
		[EnumMember(Value="version-premier-metal-3100")]
		Version_premier_metal_3100,
		
		[EnumMember(Value="version-premier-metal-3200")]
		Version_premier_metal_3200,
		
		[EnumMember(Value="version-premier-metal-3300")]
		Version_premier_metal_3300,
		
		[EnumMember(Value="version-premier-metal-3400")]
		Version_premier_metal_3400,
		
		[EnumMember(Value="version-premier-metal-3500")]
		Version_premier_metal_3500,
		
		[EnumMember(Value="version-premier-metal-3600")]
		Version_premier_metal_3600,
		
		[EnumMember(Value="version-premier-metal-3700")]
		Version_premier_metal_3700,
		
		[EnumMember(Value="version-premier-metal-3800")]
		Version_premier_metal_3800,
		
		[EnumMember(Value="version-premier-metal-3900")]
		Version_premier_metal_3900,
		
		[EnumMember(Value="version-premier-metal-400")]
		Version_premier_metal_400,
		
		[EnumMember(Value="version-premier-metal-4000")]
		Version_premier_metal_4000,
		
		[EnumMember(Value="version-premier-metal-4100")]
		Version_premier_metal_4100,
		
		[EnumMember(Value="version-premier-metal-4200")]
		Version_premier_metal_4200,
		
		[EnumMember(Value="version-premier-metal-4300")]
		Version_premier_metal_4300,
		
		[EnumMember(Value="version-premier-metal-4400")]
		Version_premier_metal_4400,
		
		[EnumMember(Value="version-premier-metal-4500")]
		Version_premier_metal_4500,
		
		[EnumMember(Value="version-premier-metal-4600")]
		Version_premier_metal_4600,
		
		[EnumMember(Value="version-premier-metal-4700")]
		Version_premier_metal_4700,
		
		[EnumMember(Value="version-premier-metal-4800")]
		Version_premier_metal_4800,
		
		[EnumMember(Value="version-premier-metal-4900")]
		Version_premier_metal_4900,
		
		[EnumMember(Value="version-premier-metal-500")]
		Version_premier_metal_500,
		
		[EnumMember(Value="version-premier-metal-5000")]
		Version_premier_metal_5000,
		
		[EnumMember(Value="version-premier-metal-5100")]
		Version_premier_metal_5100,
		
		[EnumMember(Value="version-premier-metal-5200")]
		Version_premier_metal_5200,
		
		[EnumMember(Value="version-premier-metal-5300")]
		Version_premier_metal_5300,
		
		[EnumMember(Value="version-premier-metal-5400")]
		Version_premier_metal_5400,
		
		[EnumMember(Value="version-premier-metal-5500")]
		Version_premier_metal_5500,
		
		[EnumMember(Value="version-premier-metal-5600")]
		Version_premier_metal_5600,
		
		[EnumMember(Value="version-premier-metal-5700")]
		Version_premier_metal_5700,
		
		[EnumMember(Value="version-premier-metal-5800")]
		Version_premier_metal_5800,
		
		[EnumMember(Value="version-premier-metal-5900")]
		Version_premier_metal_5900,
		
		[EnumMember(Value="version-premier-metal-600")]
		Version_premier_metal_600,
		
		[EnumMember(Value="version-premier-metal-6000")]
		Version_premier_metal_6000,
		
		[EnumMember(Value="version-premier-metal-6100")]
		Version_premier_metal_6100,
		
		[EnumMember(Value="version-premier-metal-6200")]
		Version_premier_metal_6200,
		
		[EnumMember(Value="version-premier-metal-6300")]
		Version_premier_metal_6300,
		
		[EnumMember(Value="version-premier-metal-6400")]
		Version_premier_metal_6400,
		
		[EnumMember(Value="version-premier-metal-6500")]
		Version_premier_metal_6500,
		
		[EnumMember(Value="version-premier-metal-6600")]
		Version_premier_metal_6600,
		
		[EnumMember(Value="version-premier-metal-6700")]
		Version_premier_metal_6700,
		
		[EnumMember(Value="version-premier-metal-6800")]
		Version_premier_metal_6800,
		
		[EnumMember(Value="version-premier-metal-6900")]
		Version_premier_metal_6900,
		
		[EnumMember(Value="version-premier-metal-700")]
		Version_premier_metal_700,
		
		[EnumMember(Value="version-premier-metal-7000")]
		Version_premier_metal_7000,
		
		[EnumMember(Value="version-premier-metal-7100")]
		Version_premier_metal_7100,
		
		[EnumMember(Value="version-premier-metal-7200")]
		Version_premier_metal_7200,
		
		[EnumMember(Value="version-premier-metal-7300")]
		Version_premier_metal_7300,
		
		[EnumMember(Value="version-premier-metal-7400")]
		Version_premier_metal_7400,
		
		[EnumMember(Value="version-premier-metal-7500")]
		Version_premier_metal_7500,
		
		[EnumMember(Value="version-premier-metal-7600")]
		Version_premier_metal_7600,
		
		[EnumMember(Value="version-premier-metal-7700")]
		Version_premier_metal_7700,
		
		[EnumMember(Value="version-premier-metal-7800")]
		Version_premier_metal_7800,
		
		[EnumMember(Value="version-premier-metal-7900")]
		Version_premier_metal_7900,
		
		[EnumMember(Value="version-premier-metal-800")]
		Version_premier_metal_800,
		
		[EnumMember(Value="version-premier-metal-8000")]
		Version_premier_metal_8000,
		
		[EnumMember(Value="version-premier-metal-8100")]
		Version_premier_metal_8100,
		
		[EnumMember(Value="version-premier-metal-8200")]
		Version_premier_metal_8200,
		
		[EnumMember(Value="version-premier-metal-8300")]
		Version_premier_metal_8300,
		
		[EnumMember(Value="version-premier-metal-8400")]
		Version_premier_metal_8400,
		
		[EnumMember(Value="version-premier-metal-8500")]
		Version_premier_metal_8500,
		
		[EnumMember(Value="version-premier-metal-8600")]
		Version_premier_metal_8600,
		
		[EnumMember(Value="version-premier-metal-8700")]
		Version_premier_metal_8700,
		
		[EnumMember(Value="version-premier-metal-8800")]
		Version_premier_metal_8800,
		
		[EnumMember(Value="version-premier-metal-8900")]
		Version_premier_metal_8900,
		
		[EnumMember(Value="version-premier-metal-900")]
		Version_premier_metal_900,
		
		[EnumMember(Value="version-premier-metal-9000")]
		Version_premier_metal_9000,
		
		[EnumMember(Value="version-premier-metal-9100")]
		Version_premier_metal_9100,
		
		[EnumMember(Value="version-premier-metal-9200")]
		Version_premier_metal_9200,
		
		[EnumMember(Value="version-premier-metal-9300")]
		Version_premier_metal_9300,
		
		[EnumMember(Value="version-premier-metal-9400")]
		Version_premier_metal_9400,
		
		[EnumMember(Value="version-premier-metal-9500")]
		Version_premier_metal_9500,
		
		[EnumMember(Value="version-premier-metal-9600")]
		Version_premier_metal_9600,
		
		[EnumMember(Value="version-premier-metal-9700")]
		Version_premier_metal_9700,
		
		[EnumMember(Value="version-premier-metal-9800")]
		Version_premier_metal_9800,
		
		[EnumMember(Value="version-premier-metal-9900")]
		Version_premier_metal_9900,
		
		[EnumMember(Value="version-pro-cloud")]
		Version_pro_cloud,
		
		[EnumMember(Value="version-solo-cloud")]
		Version_solo_cloud,
		
		[EnumMember(Value="version-solo-metal")]
		Version_solo_metal,
	}
	
	/// <summary>
	/// All states a license can be in
	/// </summary>
	public enum LicenseStateEnum {
		
		[EnumMember(Value="ok")]
		Ok,
		
		[EnumMember(Value="released")]
		Released,
		
		[EnumMember(Value="terminated")]
		Terminated,
		
		[EnumMember(Value="toDeliver")]
		ToDeliver,
	}
	
	/// <summary>
	/// All states a license Task can be in
	/// </summary>
	public enum LicenseTaskStateEnum {
		
		[EnumMember(Value="cancelled")]
		Cancelled,
		
		[EnumMember(Value="doing")]
		Doing,
		
		[EnumMember(Value="done")]
		Done,
		
		[EnumMember(Value="error")]
		Error,
		
		[EnumMember(Value="todo")]
		Todo,
	}
	
	/// <summary>
	/// Detailed renewal type of a service
	/// </summary>
	public enum ServiceRenewalTypeEnum {
		
		[EnumMember(Value="automaticForcedProduct")]
		AutomaticForcedProduct,
		
		[EnumMember(Value="automaticV2012")]
		AutomaticV2012,
		
		[EnumMember(Value="automaticV2014")]
		AutomaticV2014,
		
		[EnumMember(Value="automaticV2016")]
		AutomaticV2016,
		
		[EnumMember(Value="manual")]
		Manual,
		
		[EnumMember(Value="oneShot")]
		OneShot,
		
		[EnumMember(Value="option")]
		Option,
	}
	
	public enum ServiceStateEnum {
		
		[EnumMember(Value="expired")]
		Expired,
		
		[EnumMember(Value="inCreation")]
		InCreation,
		
		[EnumMember(Value="ok")]
		Ok,
		
		[EnumMember(Value="pendingDebt")]
		PendingDebt,
		
		[EnumMember(Value="unPaid")]
		UnPaid,
	}
	
	/// <summary>
	/// All future uses you can provide for a service termination
	/// </summary>
	public enum ServiceTerminationFutureUseEnum {
		
		[EnumMember(Value="NOT_REPLACING_SERVICE")]
		NOT_REPLACING_SERVICE,
		
		[EnumMember(Value="OTHER")]
		OTHER,
		
		[EnumMember(Value="SUBSCRIBE_AN_OTHER_SERVICE")]
		SUBSCRIBE_AN_OTHER_SERVICE,
		
		[EnumMember(Value="SUBSCRIBE_OTHER_KIND_OF_SERVICE_WITH_COMPETITOR")]
		SUBSCRIBE_OTHER_KIND_OF_SERVICE_WITH_COMPETITOR,
		
		[EnumMember(Value="SUBSCRIBE_SIMILAR_SERVICE_WITH_COMPETITOR")]
		SUBSCRIBE_SIMILAR_SERVICE_WITH_COMPETITOR,
	}
	
	/// <summary>
	/// All reasons you can provide for a service termination
	/// </summary>
	public enum ServiceTerminationReasonEnum {
		
		[EnumMember(Value="FEATURES_DONT_SUIT_ME")]
		FEATURES_DONT_SUIT_ME,
		
		[EnumMember(Value="LACK_OF_PERFORMANCES")]
		LACK_OF_PERFORMANCES,
		
		[EnumMember(Value="MIGRATED_TO_ANOTHER_OVH_PRODUCT")]
		MIGRATED_TO_ANOTHER_OVH_PRODUCT,
		
		[EnumMember(Value="MIGRATED_TO_COMPETITOR")]
		MIGRATED_TO_COMPETITOR,
		
		[EnumMember(Value="NOT_ENOUGH_RECOGNITION")]
		NOT_ENOUGH_RECOGNITION,
		
		[EnumMember(Value="NOT_NEEDED_ANYMORE")]
		NOT_NEEDED_ANYMORE,
		
		[EnumMember(Value="NOT_RELIABLE")]
		NOT_RELIABLE,
		
		[EnumMember(Value="NO_ANSWER")]
		NO_ANSWER,
		
		[EnumMember(Value="OTHER")]
		OTHER,
		
		[EnumMember(Value="PRODUCT_DIMENSION_DONT_SUIT_ME")]
		PRODUCT_DIMENSION_DONT_SUIT_ME,
		
		[EnumMember(Value="PRODUCT_TOOLS_DONT_SUIT_ME")]
		PRODUCT_TOOLS_DONT_SUIT_ME,
		
		[EnumMember(Value="TOO_EXPENSIVE")]
		TOO_EXPENSIVE,
		
		[EnumMember(Value="TOO_HARD_TO_USE")]
		TOO_HARD_TO_USE,
		
		[EnumMember(Value="UNSATIFIED_BY_CUSTOMER_SUPPORT")]
		UNSATIFIED_BY_CUSTOMER_SUPPORT,
	}
	
	/// <summary>
	/// A short description of what does the Task on your license
	/// </summary>
	public class LicenseActionType {
	}
	
	/// <summary>
	/// License change ip status return
	/// </summary>
	public class LicenseChangeIpStatus {
		
		private string Message_bfield;
		
		private bool Success_bfield;
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;license.ChangeIpMessageEnum&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("message")]
		public string Message {
			get {
				return this.Message_bfield;
			}
			set {
				this.Message_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;boolean&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("success")]
		public bool Success {
			get {
				return this.Success_bfield;
			}
			set {
				this.Success_bfield = value;
			}
		}
	}
	
	/// <summary>
	/// The serviceTypes allowed to Order a CPanel version
	/// </summary>
	public class LicenseCpanelOrderConfiguration {
		
		private string[] OrderableVersions_bfield;
		
		private string ServiceType_bfield;
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;license.OrderableCpanelCompatibilityInfos[]&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("orderableVersions")]
		public string[] OrderableVersions {
			get {
				return this.OrderableVersions_bfield;
			}
			set {
				this.OrderableVersions_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;license.LicenseTypeEnum&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("serviceType")]
		public string ServiceType {
			get {
				return this.ServiceType_bfield;
			}
			set {
				this.ServiceType_bfield = value;
			}
		}
	}
	
	/// <summary>
	/// All versions available for Cpanel products
	/// </summary>
	public class LicenseOrderableCpanelCompatibilityInfos {
		
		private string Version_bfield;
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;license.OrderableCpanelVersionEnum&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("version")]
		public string Version {
			get {
				return this.Version_bfield;
			}
			set {
				this.Version_bfield = value;
			}
		}
	}
	
	/// <summary>
	/// licenses Todos
	/// </summary>
	public class LicenseTask {
		
		private LicenseActionType Action_bfield;
		
		private System.Nullable<System.DateTime> DoneDate_bfield;
		
		private System.DateTime LastUpdate_bfield;
		
		private string Name_bfield;
		
		private string Status_bfield;
		
		private long TaskId_bfield;
		
		private System.DateTime TodoDate_bfield;
		
		/// <summary>
		/// This Task description
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;license.ActionType&quot;,&quot;Description&quot;:&quot;This Task description&quot;,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("action")]
		public LicenseActionType Action {
			get {
				return this.Action_bfield;
			}
			set {
				this.Action_bfield = value;
			}
		}
		
		/// <summary>
		/// When was this Task done
		/// {&quot;CanBeNull&quot;:true,&quot;Type&quot;:&quot;datetime&quot;,&quot;Description&quot;:&quot;When was this Task done&quot;,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("doneDate")]
		public System.Nullable<System.DateTime> DoneDate {
			get {
				return this.DoneDate_bfield;
			}
			set {
				this.DoneDate_bfield = value;
			}
		}
		
		/// <summary>
		/// The last time this Task was updated
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;datetime&quot;,&quot;Description&quot;:&quot;The last time this Task was updated&quot;,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("lastUpdate")]
		public System.DateTime LastUpdate {
			get {
				return this.LastUpdate_bfield;
			}
			set {
				this.LastUpdate_bfield = value;
			}
		}
		
		/// <summary>
		/// This Task name
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;string&quot;,&quot;Description&quot;:&quot;This Task name&quot;,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("name")]
		public string Name {
			get {
				return this.Name_bfield;
			}
			set {
				this.Name_bfield = value;
			}
		}
		
		/// <summary>
		/// Current Taks status
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;license.TaskStateEnum&quot;,&quot;Description&quot;:&quot;Current Taks status&quot;,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("status")]
		public string Status {
			get {
				return this.Status_bfield;
			}
			set {
				this.Status_bfield = value;
			}
		}
		
		/// <summary>
		/// This Task id
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;long&quot;,&quot;Description&quot;:&quot;This Task id&quot;,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("taskId")]
		public long TaskId {
			get {
				return this.TaskId_bfield;
			}
			set {
				this.TaskId_bfield = value;
			}
		}
		
		/// <summary>
		/// When was this Task created
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;datetime&quot;,&quot;Description&quot;:&quot;When was this Task created&quot;,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("todoDate")]
		public System.DateTime TodoDate {
			get {
				return this.TodoDate_bfield;
			}
			set {
				this.TodoDate_bfield = value;
			}
		}
	}
	
	/// <summary>
	/// Your Cpanel license
	/// </summary>
	public class LicensecpanelCpanel {
		
		private System.DateTime Creation_bfield;
		
		private bool DeleteAtExpiration_bfield;
		
		private string Domain_bfield;
		
		private string Ip_bfield;
		
		private string LicenseId_bfield;
		
		private string Status_bfield;
		
		private string Version_bfield;
		
		/// <summary>
		/// This license creation date
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;datetime&quot;,&quot;Description&quot;:&quot;This license creation date&quot;,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("creation")]
		public System.DateTime Creation {
			get {
				return this.Creation_bfield;
			}
			set {
				this.Creation_bfield = value;
			}
		}
		
		/// <summary>
		/// Shall we delete this on expiration ?
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;boolean&quot;,&quot;Description&quot;:&quot;Shall we delete this on expiration ?&quot;,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("deleteAtExpiration")]
		public bool DeleteAtExpiration {
			get {
				return this.DeleteAtExpiration_bfield;
			}
			set {
				this.DeleteAtExpiration_bfield = value;
			}
		}
		
		/// <summary>
		/// The internal name of your license
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;string&quot;,&quot;Description&quot;:&quot;The internal name of your license&quot;,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("domain")]
		public string Domain {
			get {
				return this.Domain_bfield;
			}
			set {
				this.Domain_bfield = value;
			}
		}
		
		/// <summary>
		/// The ip on which this license is attached
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;ipv4&quot;,&quot;Description&quot;:&quot;The ip on which this license is attached&quot;,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("ip")]
		public string Ip {
			get {
				return this.Ip_bfield;
			}
			set {
				this.Ip_bfield = value;
			}
		}
		
		/// <summary>
		/// The license id on license provider side
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;string&quot;,&quot;Description&quot;:&quot;The license id on license provider side&quot;,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("licenseId")]
		public string LicenseId {
			get {
				return this.LicenseId_bfield;
			}
			set {
				this.LicenseId_bfield = value;
			}
		}
		
		/// <summary>
		/// This license state
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;license.StateEnum&quot;,&quot;Description&quot;:&quot;This license state&quot;,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("status")]
		public string Status {
			get {
				return this.Status_bfield;
			}
			set {
				this.Status_bfield = value;
			}
		}
		
		/// <summary>
		/// This license version
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;license.CpanelVersionEnum&quot;,&quot;Description&quot;:&quot;This license version&quot;,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("version")]
		public string Version {
			get {
				return this.Version_bfield;
			}
			set {
				this.Version_bfield = value;
			}
		}
	}
	
	/// <summary>
	/// Map a possible renew for a specific service
	/// </summary>
	public class ServiceRenewType {
		
		private bool Automatic_bfield;
		
		private bool DeleteAtExpiration_bfield;
		
		private bool Forced_bfield;
		
		private System.Nullable<bool> ManualPayment_bfield;
		
		private System.Nullable<long> Period_bfield;
		
		/// <summary>
		/// The service is automatically renewed
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;boolean&quot;,&quot;Description&quot;:&quot;The service is automatically renewed&quot;,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("automatic")]
		public bool Automatic {
			get {
				return this.Automatic_bfield;
			}
			set {
				this.Automatic_bfield = value;
			}
		}
		
		/// <summary>
		/// The service will be deleted at expiration
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;boolean&quot;,&quot;Description&quot;:&quot;The service will be deleted at expiration&quot;,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("deleteAtExpiration")]
		public bool DeleteAtExpiration {
			get {
				return this.DeleteAtExpiration_bfield;
			}
			set {
				this.DeleteAtExpiration_bfield = value;
			}
		}
		
		/// <summary>
		/// The service forced to be renewed
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;boolean&quot;,&quot;Description&quot;:&quot;The service forced to be renewed&quot;,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("forced")]
		public bool Forced {
			get {
				return this.Forced_bfield;
			}
			set {
				this.Forced_bfield = value;
			}
		}
		
		/// <summary>
		/// The service needs to be manually renewed and paid
		/// {&quot;CanBeNull&quot;:true,&quot;Type&quot;:&quot;boolean&quot;,&quot;Description&quot;:&quot;The service needs to be manually renewed and paid&quot;,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("manualPayment")]
		public System.Nullable<bool> ManualPayment {
			get {
				return this.ManualPayment_bfield;
			}
			set {
				this.ManualPayment_bfield = value;
			}
		}
		
		/// <summary>
		/// period of renew in month
		/// {&quot;CanBeNull&quot;:true,&quot;Type&quot;:&quot;long&quot;,&quot;Description&quot;:&quot;period of renew in month&quot;,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("period")]
		public System.Nullable<long> Period {
			get {
				return this.Period_bfield;
			}
			set {
				this.Period_bfield = value;
			}
		}
	}
	
	/// <summary>
	/// Details about a Service
	/// </summary>
	public class ServicesService {
		
		private bool CanDeleteAtExpiration_bfield;
		
		private string ContactAdmin_bfield;
		
		private string ContactBilling_bfield;
		
		private string ContactTech_bfield;
		
		private string Creation_bfield;
		
		private string Domain_bfield;
		
		private string EngagedUpTo_bfield;
		
		private string Expiration_bfield;
		
		private long[] PossibleRenewPeriod_bfield;
		
		private ServiceRenewType Renew_bfield;
		
		private string RenewalType_bfield;
		
		private long ServiceId_bfield;
		
		private string Status_bfield;
		
		/// <summary>
		/// Indicates that the service can be set up to be deleted at expiration
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;boolean&quot;,&quot;Description&quot;:&quot;Indicates that the service can be set up to be deleted at expiration&quot;,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("canDeleteAtExpiration")]
		public bool CanDeleteAtExpiration {
			get {
				return this.CanDeleteAtExpiration_bfield;
			}
			set {
				this.CanDeleteAtExpiration_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;string&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("contactAdmin")]
		public string ContactAdmin {
			get {
				return this.ContactAdmin_bfield;
			}
			set {
				this.ContactAdmin_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;string&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("contactBilling")]
		public string ContactBilling {
			get {
				return this.ContactBilling_bfield;
			}
			set {
				this.ContactBilling_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;string&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("contactTech")]
		public string ContactTech {
			get {
				return this.ContactTech_bfield;
			}
			set {
				this.ContactTech_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;date&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("creation")]
		public string Creation {
			get {
				return this.Creation_bfield;
			}
			set {
				this.Creation_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;string&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("domain")]
		public string Domain {
			get {
				return this.Domain_bfield;
			}
			set {
				this.Domain_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:true,&quot;Type&quot;:&quot;date&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("engagedUpTo")]
		public string EngagedUpTo {
			get {
				return this.EngagedUpTo_bfield;
			}
			set {
				this.EngagedUpTo_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;date&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("expiration")]
		public string Expiration {
			get {
				return this.Expiration_bfield;
			}
			set {
				this.Expiration_bfield = value;
			}
		}
		
		/// <summary>
		/// All the possible renew period of your service in month
		/// {&quot;CanBeNull&quot;:true,&quot;Type&quot;:&quot;long[]&quot;,&quot;Description&quot;:&quot;All the possible renew period of your service in month&quot;,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("possibleRenewPeriod")]
		public long[] PossibleRenewPeriod {
			get {
				return this.PossibleRenewPeriod_bfield;
			}
			set {
				this.PossibleRenewPeriod_bfield = value;
			}
		}
		
		/// <summary>
		/// Way of handling the renew
		/// {&quot;CanBeNull&quot;:true,&quot;Type&quot;:&quot;service.RenewType&quot;,&quot;Description&quot;:&quot;Way of handling the renew&quot;,&quot;Readonly&quot;:false}
		/// </summary>
		[JsonProperty("renew")]
		public ServiceRenewType Renew {
			get {
				return this.Renew_bfield;
			}
			set {
				this.Renew_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;service.RenewalTypeEnum&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("renewalType")]
		public string RenewalType {
			get {
				return this.RenewalType_bfield;
			}
			set {
				this.RenewalType_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;long&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("serviceId")]
		public long ServiceId {
			get {
				return this.ServiceId_bfield;
			}
			set {
				this.ServiceId_bfield = value;
			}
		}
		
		/// <summary>
		/// 
		/// {&quot;CanBeNull&quot;:false,&quot;Type&quot;:&quot;service.StateEnum&quot;,&quot;Description&quot;:null,&quot;Readonly&quot;:true}
		/// </summary>
		[JsonProperty("status")]
		public string Status {
			get {
				return this.Status_bfield;
			}
			set {
				this.Status_bfield = value;
			}
		}
	}
}
